### ISSUE TITLE
NPM Start Error

### ISSUE THREAD

**Issue by Aliiiu** [cobiwave/simplefolio#145]
After following the necessary steps and ensuring i have the required version of npm I still encounter this error
![simplefolio](https://user-images.githubusercontent.com/67792966/147894643-9ee5c9b3-432f-4fe5-9e68-f4f800aa6450.png)

**Comment by xts7** [comment]
same, nothing seems to fix

**Comment by npiyush97** [comment]
working please update dependencies 
package.json = start = parcel src/index.html
{
  "name": "simplefolio",
  "version": "1.0.1",
  "private": "true",
  "description": "A clean, beautiful and responsive portfolio template for Developers!",
  "source": "src/index.html",
  "scripts": {
    "start": "parcel src/index.html",
    "build": "parcel build"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/cobidev/simplefolio"
  },
  "keywords": [

  ],
  "author": "Jacobo Martinez",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/cobidev/simplefolio/issues"
  },
  "homepage": "https://github.com/cobidev/simplefolio#readme",
  "devDependencies": {
    "@parcel/transformer-sass": "^2.0.1",
    "parcel": "^2.0.1",
    "prettier": "^2.4.1"
  },
  "dependencies": {
    "@popperjs/core": "^2.10.2",
    "bootstrap": "^5.1.3",
    "jquery": "^3.6.0",
    "popper.js": "^1.16.1",
    "vanilla-tilt": "^1.7.2"
  }
}

**Comment by sumitvadhera01** [comment]
@npiyush97 Even I am seeing the following error, I did update the dependencies. Not sure, what it is though but similar to this- https://github.com/parcel-bundler/parcel/issues/7572
simplefolio % npm start

> simplefolio@1.0.1 start
> parcel src/index.html

Port "1234" could not be used
Server running at http://localhost:50990
🚨 Build failed.

@parcel/package-manager: Could not find module "@parcel/transformer-sass" satisfying ^2.2.1.

 simplefolio/package.json:1:513
  > 1 | es":{"@parcel/transformer-sass":"^2.0.1","parcel":"^2.2.1","prettier":"^2.4.1"},"dependencies":{"@popperjs/core":"^2.10.2","bootstrap":"^5.1.3","jquery":"^3.6.
  >   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^ Found this conflicting local requirement.

**Comment by Dr-Francis** [comment]
Alright I think I figured it out. So a lot of dependencies are obsolete and you'll have to install or update them again.

First on your terminal Run this command- npm outdated --depth=3
This will output the obsolete dependencies that needs an update.
 Install by running this command- npm install @parcel
Repeat this step and replace parcel with other dependencies you need to update.
When you're done run this command again- npm outdated --depth=3
This time you should get no output.
You can now go ahead to run 'npm start' on your terminal and this will build and launch the site on your localhost.
I hope this helps.

**Comment by nabil-github0** [comment]
> Alright I think I figured it out. So a lot of dependencies are obsolete and you'll have to install or update them again.
> 
> First on your terminal Run this command- npm outdated --depth=3 This will output the obsolete dependencies that needs an update. Install by running this command- npm install @parcel Repeat this step and replace parcel with other dependencies you need to update. When you're done run this command again- npm outdated --depth=3 This time you should get no output. You can now go ahead to run 'npm start' on your terminal and this will build and launch the site on your localhost. I hope this helps.


I did that but that solved only half of my problem then I got this

$ npm start

> simplefolio@1.0.1 start
> parcel

Error: The specified module could not be found.
\\?\C:\Users\NABIL\Desktop\simplefolio\node_modules\@parcel\source-map\parcel_sourcemap_node\artifacts\index.win32-x64-msvc.node
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1185:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (C:\Users\NABIL\Desktop\simplefolio\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\Users\NABIL\Desktop\simplefolio\node_modules\@parcel\source-map\parcel_sourcemap_node\index.js:15:18)
    at Module._compile (C:\Users\NABIL\Desktop\simplefolio\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_DLOPEN_FAILED'
}
////////What should I do now?////////////

**Comment by Benkyle** [comment]
Here is my own error 
@parcel/transformer-sass: Can't find stylesheet to import.
  ╷
1 │  @import "~bootstrap/scss/bootstrap";
  │          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\sass\vendors\\_bootstrap.scss 1:10  @import
  src\styles.scss 20:9                   root stylesheet

  Error: Can't find stylesheet to import.
    ╷
  1 │  @import "~bootstrap/scss/bootstrap";
    │          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    src\sass\vendors\_bootstrap.scss 1:10  @import
    src\styles.scss 20:9                   root stylesheet
      at Object._newRenderError 
  (C:\Users\Olan\Desktop\codes\simplefolio\node_modules\sass\sass.dart.js:16144:19)
      at Object._wrapException 
  (C:\Users\Olan\Desktop\codes\simplefolio\node_modules\sass\sass.dart.js:15964:16)
      at render_closure1.call$2 
  (C:\Users\Olan\Desktop\codes\simplefolio\node_modules\sass\sass.dart.js:82305:21)
      at _RootZone.runBinary$3$3 
  (C:\Users\Olan\Desktop\codes\simplefolio\node_modules\sass\sass.dart.js:28284:18)
      at _FutureListener.handleError$1 
  (C:\Users\Olan\Desktop\codes\simplefolio\node_modules\sass\sass.dart.js:26806:21)
      at _Future__propagateToListeners_handleError.call$0 
  (C:\Users\Olan\Desktop\codes\simplefolio\node_modules\sass\sass.dart.js:27113:49)
      at Object._Future__propagateToListeners 
  (C:\Users\Olan\Desktop\codes\simplefolio\node_modules\sass\sass.dart.js:12137:77)
      at _Future._completeError$2 
  (C:\Users\Olan\Desktop\codes\simplefolio\node_modules\sass\sass.dart.js:26959:9)
      at _AsyncAwaitCompleter.completeError$2 
  (C:\Users\Olank,\Desktop\codes\simplefolio\node_modules\sass\sass.dart.js:26618:12)
      at Object._asyncRethrow 
  (C:\Users\Olan\Desktop\codes\simplefolio\node_modules\sass\sass.dart.js:11940:17)

**Comment by cobiwave** [comment]
Hey @Aliiiu @j-t-z @npiyush97 @sumitvadhera01 @Benkyle @nabil-github0 

Sorry for replying at this late. Do you still need some help or guidance?

Right now I am working on major updates (mostly fixing all the issues Simplefolio has).

I will let know to all the community via Discord.
