### ISSUE TITLE
npm start

### ISSUE THREAD

**Issue by jacobsayono** [cobiwave/simplefolio#221]
```
> simplefolio@1.0.1 start /home/jacobsayono/simplefolio
> parcel

/home/jacobsayono/simplefolio/node_modules/@parcel/core/lib/Parcel.js:150
  #requestTracker
  ^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:83:7)
    at NativeCompileCache._moduleCompile (/home/jacobsayono/simplefolio/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/home/jacobsayono/simplefolio/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/home/jacobsayono/simplefolio/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/jacobsayono/simplefolio/node_modules/@parcel/core/lib/index.js:81:39)
/home/jacobsayono/simplefolio/node_modules/@parcel/logger/lib/Logger.js:41
  #logEmitter
  ^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:83:7)
    at NativeCompileCache._moduleCompile (/home/jacobsayono/simplefolio/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/home/jacobsayono/simplefolio/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at _logger (/home/jacobsayono/simplefolio/node_modules/parcel/lib/cli.js:54:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! simplefolio@1.0.1 start: `parcel`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the simplefolio@1.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jacobsayono/.npm/_logs/2022-11-26T07_59_52_720Z-debug.log

```

**Comment by jacobsayono** [comment]
fixed by using `nvm` to install latest version of node and npm. ubuntu's `apt` does not install latest version. this site helps with the tutorial. note that i later ran the command `nvm alias default v18.0.0` to remove annoying warnings because the terminal was reverting to the older version everytime i restarted my terminal. i also learned to update git to the latest version (not from apt, which was an older version) by using `ppa`.

now i have these on my system:
`npm --version` = 8.6.0
`node --version` = v18.0.0
`git --version` = 2.38.1

i am able to npm install and npm start. the server is running at https://localhost:1234
i opened my chrome browser to this site, but localhost sent an invalid response. to fix this, i typed `localhost:1234` on my chrome browser instead of `https://localhost:1234`

hope this helps (especially ubuntu users!)
